### ISSUE TITLE
PHP Notices on Views Display 

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/adaptive_image#2]
When creating a view that is a page where the content is displayed in a teaser mode or when just displaying fields, I get the following notices. None of the default image styles gave me these notices. 

```
Notice: Use of undefined constant pixel_density - assumed 'pixel_density' in /adaptive_image/adaptive_image.module on line 249

Notice: Undefined index: dirname in 
/adaptive_image/adaptive_image.module on line 165
```

**Comment by alexfinnarn** [comment]
...using the defaults when creating adaptive image style.

**Comment by argiepiano** [comment]
This is caused by a simple typo in line 249 in the current version. Should be `$pixel_density` rather than `pixel_density`
