### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/adaptive_image#5]
@biolithic I noticed that there hasn't been any activity since 2016. The D7 module has evolved. The Backdrop version is throwing several notices, and even a fatal error in PHP 8+.

Please let us know if you still intend to maintain. 

Thanks!

**Comment by jenlampton** [comment]
I would take this 1 year silence and confirmation that the project is abandoned. I have opened https://github.com/backdrop-ops/contrib/issues/793 to remove the current maintainer.
